name: Convert MD to PDF
on:
  push:
    paths:
      - 'TP1.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended

      - name: Prepare markdown
        run: |
          # Copy the file and fix absolute image paths starting with /img/ -> img/
          cp TP1.md TP1-for-pdf.md
          sed -i 's|/img/|img/|g' TP1-for-pdf.md

      - name: Convert to PDF
        run: |
          pandoc TP1-for-pdf.md -o TP1.pdf --pdf-engine=xelatex -V lang=fr -V geometry:margin=2cm

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: TP1-pdf
          path: TP1.pdf