name: Convert MD to PDF
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'TP1.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check file exists
        run: |
          echo "Checking if TP1.md exists..."
          ls -la
          if [ -f "TP1.md" ]; then
            echo "✅ TP1.md found"
          else
            echo "❌ TP1.md not found"
            exit 1
          fi
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended
      
      - name: Prepare markdown
        run: |
          cp TP1.md TP1-for-pdf.md
          sed -i 's|/img/|img/|g' TP1-for-pdf.md
          echo "Content prepared:"
          head -n 5 TP1-for-pdf.md
      
      - name: Convert to PDF
        run: |
          pandoc TP1-for-pdf.md -o TP1.pdf --pdf-engine=xelatex -V lang=fr -V geometry:margin=2cm
      
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: TP1-pdf
          path: TP1.pdf